### ISSUE TITLE
Add more information to README

### ISSUE THREAD

**Issue by cormullion** [cormullion/Zalgo.jl#2]
The README could list some of the functions and give examples. Don't think it's worth making Documenter-docs for it.

**Comment by Taneesha-creates** [comment]
Can I work on this for hacktoberfest?

**Comment by cormullion** [comment]
Yes of course! :) But make sure you've registered or whatever you have to do before you do stuff, in case your efforts aren't recognised...

**Comment by Taneesha-creates** [comment]
> Yes of course! :) But make sure you've registered or whatever you have to do before you do stuff, in case your efforts aren't recognised...

Thank you so much!
